### PR TITLE
Added summary in english

### PR DESCRIPTION
**Pull request by MayuriKolhe-2003**
Please accept my PR.

### CODE REVIEW

**Comment by JRudransh** [comment]
Your summery is great, try to create summery in hindi as well

**Comment by bhagirath77** [comment]
Will you not merge it? Or will you only merge it after hacktoberfest is over intentionally ?

**Comment by JRudransh** [comment]
I am not the owner of this repo

**Comment by Gupta-Anubhav12** [comment]
Hey the summary looks good, can we do this in JSON format aswell ?, this way we can use this in our API

**Pull request merged**
