### PR TITLE
Added Sanskrit recitation of verses chapter wise

### PR DESCRIPTION
**Pull request by Adityagupta1625**
I heave added all verses chapterwise in seperate folders.

### CODE REVIEW

**Comment by Gupta-Anubhav12** [comment]
Hey @Adityagupta1625  thanks for this wonderful contribution, but there is some inconsistency rn, that has to be manually removed, some verses were clubbed originally (in audio) and hence no of recitations are less than verses in text.
I'll look into this then approve for a final merge

**Comment by Adityagupta1625** [comment]
Sure, I can help you in this  if you want

**Comment by Gupta-Anubhav12** [comment]
it's quite hard work to cut merge and make each verse apt to our version manually 
It took me around 30 mins for a single chapter, hope It'll be done soon.
if you are willing, you can cross check and adjust the audio , 
Many thanks

**Comment by Adityagupta1625** [comment]
Yeah! for sure

**Comment by Gupta-Anubhav12** [comment]
I'm on chapter 11 rn, It'll take another hour or so, but it's done now :eyeglasses:

**Comment by Gupta-Anubhav12** [comment]
Phew Phew
It's done

**Comment by Gupta-Anubhav12** [comment]
[this](https://github.com/Adityagupta1625/gita/pull/1)

**Comment by narenderkumarrajput** [comment]
Hi @Gupta-Anubhav12 and @Adityagupta1625 
Can you please tell me which website you got these audio files from and where you copied them from? I want to verify the licenses because I need to use some of these audio files, though not all of them.

**Pull request merged**
