### PR TITLE
fix--[BUG] Text, translations and commentaries, all have the chapter …

### PR DESCRIPTION
**Pull request by Amritpal2001**
…and verse numbers at the beginning of the text#7

### CODE REVIEW

**Comment by samanyougarg** [comment]
@Amritpal2001 Is this ready to go or are we waiting for something?

**Comment by samanyougarg** [comment]
@Amritpal2001 Could you help with one more thing, please?

If you see each translation/commentary has a variable number of "\n" characters at the end. Could you please make a quick script that removes all these newlines from all the translations, commentaries, and wherever else you see it?

Screenshot 2021-12-30 at 10 23 04 AM

**Comment by Amritpal2001** [comment]
Sure sir, will be removing the "\n" characters. 
Also it seems that data has been changed. So will be again running the script on new data and will be pushing it to a new branch.
Thanks

**Comment by samanyougarg** [comment]
Sure @Amritpal2001!
Thank you :)

**Comment by Gupta-Anubhav12** [comment]
https://github.com/gita/gita/tree/fix--cleaned-data has latest data
will merge that instead of this

**Pull request closed without merging**
